name: KotlinLoginSecurity
version: 1.0
author: paranoidcake
main: com.paranoidcake.KotlinLoginSecurity.Main
api-version: 1.14
commands:
  register:
    aliases: [reg]
    description: "Register your username"
    usage: "Usage: /register <password>"
  login:
    description: "Login to your account"
    usage: "Usage: /login <password>"
  addjail:
    description: "Add a pre-login jail"
    usage: "Usage /addjail [spawn | position]"
  listjails:
    aliases: [lsjails]
    description: "List all current pre-login jail IDs and positions"
    usage: "Usage /listjails"
  removejail:
    aliases: [rmjail]
    description: "Removes the specified pre-login jail"
    usage: "Usage /removejail <jailID>"
  unregister:
    aliases: [unreg]
    description: "Unregisters your username"
    usage: "Usage: /unregister"