name: kotlinLoginSecurity
version: 1.0
author: paranoidcake
main: com.paranoidcake.kotlinLoginSecurity.Main
api-version: 1.14
commands:
  register:
    aliases: [reg]
    description: "Registers your username"
    usage: "Usage: /register <password>"
  login:
    description: "Logs in to your account"
    usage: "Usage: /login <password>"
  addjail:
    description: "Adds a pre-login jail"
    usage: "Usage /addjail [spawn | position]"
  listjails:
    aliases: [lsjails]
    description: "Lists all current pre-login jail IDs and positions"
    usage: "Usage /listjails"
  removejail:
    aliases: [rmjail]
    description: "Removes the specified pre-login jail"
    usage: "Usage /removejail <jailID>"